name: DeployMainFunc1

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
 AZURE_FUNCTIONAPP_NAME: 'ImageStorageFunctiondev'
 AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
 DOTNET_VERSION: '6.0' # set this to the dotnet version to use
 SLOT_NAME: 'Production'
 WORKING_DIRECTORY: 'HHAzureImageStorage'
 BUILD_ENVIRONMENT: 'Release'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Dependencies then Build and run tests'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration ${{ env.BUILD_ENVIRONMENT}} --output ./output          
          dotnet test
          popd          
        working-directory: ${{ env.WORKING_DIRECTORY}}
          
      - name: 'Deploy to azure'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_MAINFUNC }}
          package: .
